### ISSUE TITLE
How to send data back as acknowledgement

### ISSUE THREAD

**Issue by georgemakrakis** [flowchain/flowchain-ledger#10]
Hello,

I recently run the examples that are described at wiki (https://github.com/flowchain/flowchain-ledger/wiki) and all works fine. I was wondering if it's possible to send an acknowledgement inside **onmessage** event callback in **peer.js** file. I am running a slightly modified version of this example: https://github.com/flowchain/flowchain-ledger/wiki/3.-Send-IoT-Data-to-the-P2P-Network an i want after each message send and received by peer to send the ack.

Thanks in advance!

**Comment by jollen** [comment]
Hi @georgemakrakis ,

I have already sent a commit to figure out this issue. The nodes (both of peer and boot nodes) can create a ACK message and send it back to the sender node. You can see the ACK message.

```
[Blockchain] { message: 
   { key: 'd0adff6a11602866d7c2f58cce298283e78e50bd',
     status: 'ACK',
     id: 'ca3e159327e1446701f5d6a56b34aed71a8e6265' },
  from: 
   { address: 'localhost',
     port: 8000,
     id: 'ca3e159327e1446701f5d6a56b34aed71a8e6265' },
  source: { address: 'localhost', port: '9000' } } is found at Block#1
```

Cheers!

**Comment by georgemakrakis** [comment]
Great i will check it out! Thanks a lot! :+1:
