### ISSUE TITLE
What is finger table and chord ring?

### ISSUE THREAD

**Issue by djKooks** [flowchain/flowchain-ledger#5]
Hello.
I'm looking on current code, and cannot understand some part in boot.
What does 'finger table' and 'chord ring' means? Can I find it on your paper?

**Comment by jollen** [comment]
Hi @djKooks 

Please refer to the following figure. It may be able to answer your question in one figure.

* The finger table is the hash table (aka DHT) that each node uses the finger table to find its *successor* node. 
* In short, the finger table can organize the p2p network geometrically in a Ring topology. The p2p algorithm is called Chord, which is initially published by MIT at 2001, that we conventionally say "Chord Ring"

You can also find some useful information on my paper too ;-)

![2017-07-14 5 46 15](https://user-images.githubusercontent.com/1126021/28207461-6225250e-68bc-11e7-9134-f401719d9627.png)

**Comment by djKooks** [comment]
@jollen Thanks! I'll look on it.
