### ISSUE TITLE
Transaction data

### ISSUE THREAD

**Issue by doowb** [flowchain/flowchain-ledger#6]
I've followed the steps to run the boot node and a few peer nodes and send transaction data to the nodes. I'm trying to understand how I can get the data out of the blocks and how to connect an endpoint (as described in the whitepaper) that will receive the validated transactions to do further processing.

**Comment by jollen** [comment]
Flowchain nodes need to implement the `onquery` callback to query the data of the key and send back the data to the caller node. The node which needs to get the data out of the blocks has to keep and maintain the key.
