### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by 3Mohammed2013** [flowchain/flowchain-ledger#8]
Hello 
I have problem which file I wil use to start the flowchian ledger , there are many file like , p2p , consensus , nodes and so else ,,, i was try the commands but it not works I hope anyone can help me to fix the problem basically the issues how can i run the flowchain ledger a

Warm regards
Mohammed

**Comment by jollen** [comment]
Hi Mohammed,

You will use `boot.js` to start a boot node and then use `node.js` to start a p2p net for joining a boot node. You can follow the `How to Use` in the README. Please try `boot.js` first to check out whether there is any error.

```
$ git clone https://github.com/flowchain/flowchain-ledger.git
$ cd flowchain-ledger
$ npm install
$ export HOST=192.168.1.1
$ export PORT=8000
$ node boot.js
```

If errors occurred, please paste the console message that I can try to help.

Best,
Jollen

**Comment by 3Mohammed2013** [comment]
Hi Jollen
I was did precisely this “how to use “ and it work with me properly but, what the next step how I know if I run the flowchian ledger or not and how can I add node to my ledgers,
I need elaborate for the next steps and ,what I was read on you research that the flow chain definitely should be run web of thing and there are no clear steps to run the wot


Warm regards
Mohammed
_____________________________

**Comment by jollen** [comment]
@3Mohammed2013 

The web of things is the underlying layer of flowchain-ledger. It means that the web of things server is running when the node was started.

Also, you can try to add more peers to the networks for a next step.
